### ISSUE TITLE
How to receive  tracker data and ultrasound images from PLUS server simultaneously in matlab?

### ISSUE THREAD

**Issue by lineshen199466** [PlusToolkit/PlusMatlabUtils#1]
Hi, 
Thank you for sharing the code.
But, I have a problem that whether I can receive US images and tracker data simultaneously in matab.
If it is ok, how to receive US images in matlab?
Thank you,
Ziheng Shen

**Comment by lassoan** [comment]
You can receive images and tracking data through OpenIGTLink in Matlab. However, I would strongly recommend to use Python instead.

Note that Slicer has Python built in, so you can do any real-time image and tracking data processing there in Python. Slicer can also record data and visualize complex 3D data in real-time, and it's completely free and open-source. Matlab has none of these, so it just does not make much sense to still cling on to Matlab nowadays. We mainly make Matlab utils and bridges available to make it easier to transition from Matlab to Python.

**Comment by lineshen199466** [comment]
Thank your answer, lassoan.
I can send tracker data and images to Slicer by Plus and OpenGTLink. However, I don't know how to save them to local file. So can you provide more information or relevant materials?
Thank you again,
Ziheng Shen.

**Comment by lineshen199466** [comment]
Maybe I am more familiar with Matlab, and less familiar with python.
I still want to know, if we choose OpenIGTLink in Matlab to receive transmission and images. Whether are there any examples to refer?
Thank you,
Ziheng Shen.

**Comment by lassoan** [comment]
See OpenIGTLink implementation in Matlab here: https://github.com/PlusToolkit/PlusMatlabUtils/tree/master/MatlabOpenIGTLinkInterface

There are Matlab readers for tracked ultrasound data files (sequence metafile, .mha or .nrrd) that Plus saves (https://github.com/PlusToolkit/PlusMatlabUtils/tree/master/MatlabMetafileIO).

You can use PlusRemote module in Slicer to request Plus to start/stop recording to file.

Unless you retire soon years, it probably makes sense to learn Python instead of entrenching yourself further into Matlab.

**Comment by lineshen199466** [comment]
Thank you again.  Your suggestion is nice.
